[fmt]
ignore = ["target", "node_modules"]

[fmt.rust]
edition = "2024"
max_width = 100
hard_tabs = true
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true

[fmt.oxfmt]
use_tabs = true
tab_width = 2
